<a href="https://colab.research.google.com/github/MarvinAntillon97/datawarehouse-seguros/blob/main/Clientes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

CLIENTES

https://raw.githubusercontent.com/MarvinAntillon97/etl-data-pipeline/refs/heads/main/data/raw/clientes.csv

In [1]:
import pandas as pd

In [2]:
#Conectar con PostGresql
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_ad3f_user:dfCEzp79Czz4SFMCXmINhlJs1gBDNT9G@dpg-d6qu7s450q8c73bpf58g-a.oregon-postgres.render.com/etl_seguros_ad3f"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 31.7 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

In [3]:
url_clientes = "https://raw.githubusercontent.com/MarvinAntillon97/etl-data-pipeline/main/data/raw/clientes.csv"

clientes = pd.read_csv(url_clientes)

clientes.head()

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,01-02-80,Sta. Ana,NaN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,NaN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945/08/02,San Salvador,Pyme

In [4]:
#Limpieza de datos
clientes = clientes.copy()

clientes.columns = clientes.columns.str.strip().str.lower()

for col in clientes.select_dtypes(include='object').columns:
    clientes[col] = clientes[col].astype(str).str.strip()

clientes = clientes.replace(r'^\s*$', pd.NA, regex=True)

In [5]:
# Email
clientes['email'] = clientes['email'].str.lower()

# Fecha
clientes['fecha_nacimiento'] = pd.to_datetime(
    clientes['fecha_nacimiento'], errors='coerce'
)

# Género
map_genero = {
    "hombre": "Masculino",
    "masculino": "Masculino",
    "m": "Masculino",
    "mujer": "Femenino",
    "femenino": "Femenino",
    "f": "Femenino"
}

clientes['genero'] = clientes['genero'].str.lower().map(map_genero)
clientes['genero'] = clientes['genero'].fillna("No especificado")

# Ciudad
map_ciudad = {
    "sanmiguel": "San Miguel",
    "s. miguel": "San Miguel",
    "san miguel": "San Miguel",
    "sta. ana": "Santa Ana",
    "sta ana": "Santa Ana",
    "santa ana": "Santa Ana",
    "ss": "San Salvador",
    "san salvador": "San Salvador"
}

clientes['ciudad'] = clientes['ciudad'].str.lower().replace(map_ciudad)
clientes['ciudad'] = clientes['ciudad'].str.title()

# Segmento
clientes['segmento'] = clientes['segmento'].fillna("No especificado")

# Quitar duplicados
clientes = clientes.drop_duplicates()

In [6]:
clientes.head()

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Masculino,2011-11-24,San Miguel,nan
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,No especificado,NaT,Santa Ana,nan
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,NaT,San Miguel,nan
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,NaT,Lalibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,No especificado,1945-08-02,San Salvador,Pyme

In [7]:
clientes.isnull().sum()

id_cliente             0
nombre                 0
email                  0
genero                 0
fecha_nacimiento    2445
ciudad                 0
segmento               0
dtype: int64

In [8]:
clientes_validos = clientes[
    clientes['nombre'].notna() &
    clientes['email'].notna()
].copy()

clientes_rechazados = clientes[
    clientes['nombre'].isna() |
    clientes['email'].isna()
].copy()

In [9]:
def motivo(row):
    motivos = []

    if pd.isna(row['nombre']):
        motivos.append("nombre_vacio")

    if pd.isna(row['email']):
        motivos.append("email_vacio")

    return ",".join(motivos)

clientes_rechazados["motivo_rechazo"] = clientes_rechazados.apply(motivo, axis=1)

In [10]:
clientes_validos.to_csv("clientes_curated.csv", index=False)
clientes_rechazados.to_csv("clientes_rejects.csv", index=False)

In [11]:
pd.read_sql("SELECT * FROM clientes_rejects LIMIT 10", engine)

Empty DataFrame
Columns: [id_cliente, nombre, email, genero, fecha_nacimiento, ciudad, segmento, motivo_rechazo]
Index: []